// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsxSue-644-wBnFBglXAIB-ZbQsjOcvOo',
    appId: '1:979225287448:web:a30fc1a19d4f450212dc6d',
    messagingSenderId: '979225287448',
    projectId: 'slug-teach',
    authDomain: 'slug-teach.firebaseapp.com',
    storageBucket: 'slug-teach.appspot.com',
    measurementId: 'G-EPMKFXDS43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGI9lA1C4kYv7vFTJMmystgCSNrtKNqxE',
    appId: '1:979225287448:android:bc9d2938e6c995a512dc6d',
    messagingSenderId: '979225287448',
    projectId: 'slug-teach',
    storageBucket: 'slug-teach.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp3qaMkc_SEi4uozciQRA7MqA1HkfmRMM',
    appId: '1:979225287448:ios:c0f00813f8fbceb112dc6d',
    messagingSenderId: '979225287448',
    projectId: 'slug-teach',
    storageBucket: 'slug-teach.appspot.com',
    iosBundleId: 'com.example.slugTeach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp3qaMkc_SEi4uozciQRA7MqA1HkfmRMM',
    appId: '1:979225287448:ios:53dfe557f687e45b12dc6d',
    messagingSenderId: '979225287448',
    projectId: 'slug-teach',
    storageBucket: 'slug-teach.appspot.com',
    iosBundleId: 'com.example.slugTeach.RunnerTests',
  );
}
